[HaJunYoo][WEEK 01] 리트코드 문제 풀이
DaleStudy/leetcode-study pull request #303
Opened 2024-08-11 17:11 UTC by HaJunYoo

* [x]  [Contains Duplicate #217](https://github.com/DaleStudy/leetcode-study/issues/217)
 * [ ]   [Number of 1 Bits #232](https://github.com/DaleStudy/leetcode-study/issues/232)
 * [ ]   [Top K Frequent Elements #237](https://github.com/DaleStudy/leetcode-study/issues/237)
 * [ ]   [Kth Smallest Element In a Bst #252](https://github.com/DaleStudy/leetcode-study/issues/252)
 * [ ]   [Palindromic Substrings #267](https://github.com/DaleStudy/leetcode-study/issues/267)

2024-08-11 17:22 UTC, YeonguChoe commented
3줄로 google coding style에 맞춰서 잘 푸셨네요.

2024-08-11 17:47 UTC, HaJunYoo commented
[`google coding style`](https://google.github.io/styleguide/pyguide.html)
참고해보겠습니다 :)

2024-08-12 13:51 UTC, yolophg commented
안녕하세요, 코치 Helena 입니다.
아직 풀이가 다 완료되신 것 같지 않은데, draft로 변경해주시면 감사드리겠습니다 :)

2024-08-12 15:51 UTC, yolophg commented
추가로, 아래 사진과 같이 Projects 에서 project와 iteration 설정도 같이 부탁드립니다! 
이번엔 제가 해두었는데, 원할한 스터디 그룹 진도 관리와 통계를 위해서 중요한 부분이니 다음 이터레이션부터는 해주시면 감사드리겠습니다 :) 
![Screenshot 2024-08-12 at 11 48 15](https://github.com/user-attachments/assets/80bdcb3f-bc70-48dc-aec5-ac0cf04be412)
![Screenshot 2024-08-12 at 11 41 08](https://github.com/user-attachments/assets/3f25a7ec-76e2-40f7-ab5c-9270e1879472)

2024-08-13 16:39 UTC, HaJunYoo commented
확인했습니다!

2024-08-13 23:30 UTC, obzva commented on number-of-1-bits/hajunyoo.py
안녕하세요 HajunYoo님
`n = int(n)` 코드를 작성하신 이유가 궁금합니다 :)
제 생각엔 `def hammingWeight(self, n: int) -> int:`에서 parameter `n`을 `int`로 받고 있기 때문에 굳이 적지 않아도 될 코드 같아요

2024-08-16 00:32 UTC, yolophg commented
> @yolophg 제가 OT 때, 한국 시간 저녁 10시로 잘못 알아서 참여를 못했습니다 ..! https://github.com/orgs/DaleStudy/teams/leetcode
> 
> 팀 페이지로 들어가면 아래와 같이 뜨는데요..! 혹시 inivitation은 어디서 확인할 수 있을까요?
> 
> <img alt="스크린샷 2024-08-16 오전 12 29 34" width="1174" src="https://private-user-images.githubusercontent.com/58240677/358283789-bc271619-1953-40d7-8ad9-10f08ba8c381.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3Njg0NTcsIm5iZiI6MTcyMzc2ODE1NywicGF0aCI6Ii81ODI0MDY3Ny8zNTgyODM3ODktYmMyNzE2MTktMTk1My00MGQ3LThhZDktMTBmMDhiYThjMzgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDAwMjkxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkNTc0NDAwYTM5YTI3OTNlNjlkODM4NDg2N2YyZWI5ZWE4YmMwN2NjNzQ4MzRiNzA3YWI5ZTNlNmVhNTMyYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GAzhwg1r0nY8fOwPlqGadslORhJG-YPwpo7ny35pVFc">

아, 그렇군요. 아래 코멘트와 공지에서 확인하실 수 있듯이, 온보딩을 참석하신 분들을 최종 멤버로 확정하여 스터디 2기를 진행한다고 공지를 드렸었답니다! 그래서, 참석을 못하셔서 아마 최종 멤버로 확정되지 않아, invitation 대상에서 제외되신 듯 한데 이와 관련해서는 일단 달레님과도 논의를 해보고 공유드릴 수 있을 것 같아요.
https://github.com/DaleStudy/leetcode-study/pull/321#issuecomment-2287660521
https://github.com/DaleStudy/leetcode-study/discussions/292

2024-08-16 01:37 UTC, HaJunYoo commented
넵 @yolophg 님 
해당 건은 제가 깃헙 공지를 제대로 팔로우업 하지 못한 불찰이라 🥲 
논의 후 참여가 어려울 경우, 3기에 재도전해보겠습니다!

2024-08-16 10:24 UTC, DaleSeo commented
@HaJunYoo 님, 제가 디스코드로 DM 드렸는데 좀 확인 해주시겠습니까?

2024-08-16 10:43 UTC, HaJunYoo commented
넵 답변드렸습니다! @DaleSeo

2024-08-17 07:05 UTC, leokim0922 approved these changes

2024-08-17 07:20 UTC, obzva requested changes
Big-O notation에 대한 코멘트 추가해주시면 될 것 같습니다 ㅎㅎ

2024-08-17 07:20 UTC, obzva commented on top-k-frequent-elements/hajunyoo.py
> +        counter_dict = defaultdict(int)
collections의 `Counter`를 쓰는 건 어떨지 조심스레 제안드립니다 :)

2024-08-17 12:55 UTC, HaJunYoo commented on kth-smallest-element-in-a-bst/hajunyoo.py
> +        self.count = 0
리트코드에서 count를 그냥 선언하면 지역 변수라서 읽어오지를 못했습니다!
global로 선언해도 동일해서, 인스턴수 변수로 관리해보았습니다

2024-08-17 13:14 UTC, HaJunYoo commented on top-k-frequent-elements/hajunyoo.py
> +        counter_dict = defaultdict(int)
리뷰 감사드립니다 ㅎㅎ
사실 Counter 써보려고 했는데, 코딩 테스트에서 중요한 순간에 혹시 해당 라이브러리가 안 떠오를 수도 있고, Counter를 쓰지 않고 라이브 코딩테스트를 요청 받을 수 있을 것 같아 위와 같이 구성해보았습니다.

2024-08-17 13:16 UTC, HaJunYoo commented on number-of-1-bits/hajunyoo.py
> +        n = int(n)
이 부분은 저도 의아했는데요
n이 string으로 인식이 되는 에러가 발생했어서, int로 type casting을 해보았습니다
나중에 한번 다시 시도해보겠습니다 ㅎㅎ

2024-08-17 13:16 UTC, HaJunYoo commented
> Big-O notation에 대한 코멘트 추가해주시면 될 것 같습니다 ㅎㅎ

추가했습니다 ㅎㅎ

2024-08-17 20:03 UTC, DaleSeo commented
@obzva 님, 남겨주셨던 피드백이 원하셨던데로 반영이 되었다면 `requested changes` 상태 좀 풀어주실 수 있으실까요? PR 병합이 불가능하네요! 모임 전까지 가급적 모든 PR을 병합하고 2주차를 시작하려고 합니다.

2024-08-17 23:03 UTC, obzva approved these changes

2024-08-19 14:23 UTC, HaJunYoo commented
![스크린샷 2024-08-19 오후 11 22 20](https://github.com/user-attachments/assets/a7b11a1f-ac7b-4f37-9d0e-0aef1322a085)
![스크린샷 2024-08-19 오후 11 22 44](https://github.com/user-attachments/assets/355c7cc2-3ea1-4475-8a40-037199024a23)

@DaleSeo  님, 아직 제가 초대가 되지 않아, merge와 iteration을 조작할 권한이 없는 것 같습니다..!
확인 부탁드립니다

2024-08-19 14:33 UTC, dev-jonghoonpark commented
@HaJunYoo 안녕하세요~

깃헙과 연결된 메일로 초대장이 갔을 것 같은데
혹시 메일로 초대장 온게 따로 없으실까요?

2024-08-20 00:01 UTC, DaleSeo commented
@HaJunYoo 제가 모임 끝나고 보내드린 Invitation이 Pending 상태로 확인되시는데 한 번 메일을 확인해보시겠어요?

![Shot 2024-08-19 at 20 00 06@2x](https://github.com/user-attachments/assets/c94663b2-dace-48f2-a197-41bc57002b52)

본 PR은 제가 대신 병합해드리도록 하겠습니다.

2024-08-20 00:02 UTC, merged