[oyeong011] Week 1
DaleStudy/leetcode-study pull request #642
Opened 2024-12-06 02:38 UTC by oyeong011

## 답안 제출 문제

- [ ] #217 
- [ ] #220 
- [ ] #237 
- [ ] #240 
- [ ] #264

## 체크 리스트

- [ ] PR을 프로젝트에 추가하고 Week를 현재 주차로 설정해주세요.
- [ ] 바로 앞에 PR을 열어주신 분을 코드 검토자로 지정해주세요.
- [ ] 문제를 모두 푸시면 프로젝트에서 Status를 `In Review`로 설정해주세요.
- [ ] 코드 검토자 1분 이상으로부터 승인을 받으셨다면 PR을 병합해주세요.

2024-12-06 07:22 UTC, obzva commented
Project의 주차 설정 부탁 드립니다
<img width="329" alt="image" src="https://github.com/user-attachments/assets/f1c75748-4f73-4cea-b0b5-e1fa9d29393e">

2024-12-07 23:48 UTC, EgonD3V requested changes

2024-12-07 23:48 UTC, EgonD3V commented on top-k-frequent-elements/oyeong011.cpp
> +    }
풀이가 다른 문제와 중복되어 있는 것 같습니다. 확인을 부탁 드립니다.

2024-12-08 15:16 UTC, oyeong011 commented on top-k-frequent-elements/oyeong011.cpp
> +    }
넵 수정했습니다!

2024-12-10 12:35 UTC, obzva commented
아직 제출까지 시간이 많이 남았으니 Big O 분석도 적어주시면 더 좋을 것 같습니다 :)

2024-12-14 05:12 UTC, EgonD3V approved these changes

2024-12-14 18:23 UTC, merged